# Generated by Django 5.0.2 on 2024-02-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipestep_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Sauce', 'Sauce recipes'), ('Sweets', 'Sweets recipes'), ('Seasoning', 'Seasoning recipes'), ('Drink', 'Drink Recipes'), ('Marinade', 'Marinade recipes'), ('Dough', 'Recipes for dough products'), ('Snack', 'Snack Recipes'), ('Preparation', 'Preparation recipes'), ('Main course', 'Main course recipes'), ('First course', 'First course recipes')], max_length=100),
        ),
    ]
